name: 'Deploy backend application with Helm'
description: 'Deploy backend application with Helm'

inputs:
  env:
    description: 'environment'
    required: true
  repository-uri:
    description: 'ECR repolisoty URI'
    required: true
  image-tag:
    description: 'beckend application image tag'
    required: true
  image-name:
    description: 'beckend application image name'
    required: false
    default: test1-app
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  eks-cluster:
    description: 'AWS EKS cluster name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'
    
    - name: Update kubeconfig for EKS
      shell: bash
      run: |
        aws eks update-kubeconfig \
          --name ${{ inputs.eks-cluster }} \
          --region ${{ inputs.aws-region }}
    
    - name: Deploy with Helm
      shell: bash
      run: |
        helm upgrade --install helloworld ./helm/helloworld \
          --namespace backend-helm \
          --create-namespace \
          --set image.repository=${{ inputs.repository-uri }}/${{ inputs.image-name}} \
          --set image.tag=${{ inputs.image-tag }} \
          --wait \
          --timeout 5m

    - name: Verify deployment
      shell: bash
      run: |
        helm status helloworld -n backend-helm
        kubectl get all -n backend-helm -l app.kubernetes.io/instance=helloworld